CREATE TABLE IF NOT EXISTS daily_checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    date DATE NOT NULL,
    weight DOUBLE PRECISION,
    steps INTEGER,
    workout_done BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT unique_user_date UNIQUE (user_id, date),
    CONSTRAINT fk_daily_checkins_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_date ON daily_checkins(user_id, date);
CREATE INDEX IF NOT EXISTS idx_user_created ON daily_checkins(user_id, created_at);
