CREATE TABLE IF NOT EXISTS daily_checkins (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    date DATE NOT NULL,
    weight REAL,
    steps INTEGER,
    workout_done BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT unique_user_date UNIQUE (user_id, date),
    CONSTRAINT fk_daily_checkins_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
